workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          #filters:
          #  branches:
          #    only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: npm run build
      - run: npm run test
      - run: rm -r node_modules
      - run: npm install --production
      - run: node config/CreateCircleConfig.js
      - run: mkdir karmabotdeployment
      - run: mv node_modules karmabotdeployment
      - run: mv dist karmabotdeployment
      - run: mv config karmabotdeployment
      - run: mv karmabotdeployment/config/circleci.json karmabotdeployment/config/production.json
      - run: zip -r karmabotdeployment.zip karmabotdeployment
      - save_cache:
          key: deployment-{{ checksum "karmabotdeployment.zip" }}
          paths:
            - "karmabotdeployment.zip"

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - restore_cache:
          key: deployment-{{ checksum "package.json" }}
      - run: ls
      - run: sudo pip install awscli
      - run: aws s3 cp karmabotdeployment.zip s3://karmabotdeployment/karmabotdeployment.zip
