version: 2
jobs:
  build:
    docker:
      - image: node:8.12.0
    steps:
      - checkout
      - run: echo $NODE_ENV
      - run: npm --v
      - run: node -v
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: ls node_modules
      - run: npm run build
      - run: npm run test
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo Deploying
            else
            echo "Skipping deployment."
