workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: node:8.12.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: npm run build
      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run: ls
      - restore_cache:
          key: deployment-{{ checksum "package.json" }}
      - run: npm install --production
      - save_cache:
          key: deployment-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: npm run build
      - run: echo "Create config"
      - run: echo "Package in zip"
      - run: echo "push to S3"